export const states = [
  { name: "Abia", slug: "abia" },
  { name: "Adamawa", slug: "adamawa" },
  { name: "Akwa Ibom", slug: "akwa-ibom" },
  { name: "Anambra", slug: "anambra" },
  { name: "Bauchi", slug: "bauchi" },
  { name: "Bayelsa", slug: "bayelsa" },
  { name: "Benue", slug: "benue" },
  { name: "Borno", slug: "borno" },
  { name: "Cross River", slug: "cross-river" },
  { name: "Delta", slug: "delta" },
  { name: "Ebonyi", slug: "ebonyi" },
  { name: "Edo", slug: "edo" },
  { name: "Ekiti", slug: "ekiti" },
  { name: "Enugu", slug: "enugu" },
  { name: "FCT", slug: "fct" },
  { name: "Gombe", slug: "gombe" },
  { name: "Imo", slug: "imo" },
  { name: "Jigawa", slug: "jigawa" },
  { name: "Kaduna", slug: "kaduna" },
  { name: "Kano", slug: "kano" },
  { name: "Katsina", slug: "katsina" },
  { name: "Kebbi", slug: "kebbi" },
  { name: "Kogi", slug: "kogi" },
  { name: "Kwara", slug: "kwara" },
  { name: "Lagos", slug: "lagos" },
  { name: "Nasarawa", slug: "nasarawa" },
  { name: "Niger", slug: "niger" },
  { name: "Ogun", slug: "ogun" },
  { name: "Ondo", slug: "ondo" },
  { name: "Osun", slug: "osun" },
  { name: "Oyo", slug: "oyo" },
  { name: "Plateau", slug: "plateau" },
  { name: "Rivers", slug: "rivers" },
  { name: "Sokoto", slug: "sokoto" },
  { name: "Taraba", slug: "taraba" },
  { name: "Yobe", slug: "yobe" },
  { name: "Zamfara", slug: "zamfara" }
];
